name: release

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest # 运行环境
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: './profshown_release.jar'
          target: '~/scceprofshown'
      - name: script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/scceprofshown/
            kill -9 $(ps -ef | grep profshown | grep -v grep | awk '{print $2}')
            nohup java -jar profshown_release.jar > profshown.log 2>&1 &